import "cypress-iframe";
import "./comandos/botoes";
import "./comandos/iframe";
import "./cenarios/cenário1";
import "./cenarios/cenário2";
import "./cenarios/cenário3";
import "./commands";
import "./comandos/assert";
import "./comandos/clicar";
import "./comandos/select";
import "./comandos/write";
require("cypress-xpath");
